name: Security audit
on:
  pull_request:
    paths:
      - 'Cargo.toml'
      - '**/Cargo.toml'
  # Bors related branches
  push:
    branches:
    - master
  schedule:
    - cron: '0 0 * * *'
permissions: read-all

jobs:
  security_audit:
    name: Rustsec Audit
    runs-on: ubuntu-latest
    permissions:
      # Allow the action to post about found problems
      issues: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/audit@v1
